#!/usr/bin/env node

const path = require("path");
const fs = require("fs-extra");
const fetch = require("node-fetch");
const prettier = require("prettier");
const yargs = require("yargs/yargs");
const { hideBin } = require("yargs/helpers");

// Initialize Yargs CLI command parsing
const argv = yargs(hideBin(process.argv))
  .usage("Usage: $0 <prompt> [options]")
  .command("$0 <prompt>", "Generate complete React/TypeScript codebase based on user prompt", (y) => {
    y.positional("prompt", {
      describe: "The description of what application/component to create",
      type: "string",
    });
  })
  .option("dir", {
    alias: "d",
    describe: "Target output directory to generate the files",
    type: "string",
    default: ".",
  })
  .option("provider", {
    alias: "p",
    describe: "AI Provider to use (gemini, openai, groq)",
    type: "string",
    default: "gemini",
    choices: ["gemini", "openai", "groq"],
  })
  .option("url", {
    alias: "u",
    describe: "URL of the generation backend service",
    type: "string",
  })
  .option("key", {
    alias: "k",
    describe: "Custom API key (x-app-key) for authentication with the backend",
    type: "string",
  })
  .help("h")
  .alias("h", "help")
  .example('$0 "create a login page" -d myapp')
  .example('$0 "dashboard with charts" -d mydashboard --provider gemini')
  .parse();

async function main() {
  const prompt = argv.prompt;
  if (!prompt) {
    console.error("Error: Please provide a prompt description.");
    process.exit(1);
  }

  // Resolve Configuration Priorities: CLI arguments > Environment variables > Defaults
  const rawUrl = argv.url || process.env.MYCLI_BACKEND_URL || "http://localhost:3000";
  const url = rawUrl.endsWith("/") ? `${rawUrl}generate` : `${rawUrl}/generate`;
  const key = argv.key || process.env.MYCLI_APP_KEY || process.env.APP_API_KEY || "super_secret_app_key_for_cli";
  const targetDir = path.resolve(process.cwd(), argv.dir);
  const provider = argv.provider;

  console.log(`\n==================================================`);
  console.log(`🚀 [mycli] Initializing Code Generation...`);
  console.log(`🤖 LLM Provider: ${provider}`);
  console.log(`📂 Output Directory: ${targetDir}`);
  console.log(`🎯 Prompt: "${prompt}"`);
  console.log(`==================================================\n`);

  console.log(`⏳ Contacting the AI backend service at ${rawUrl}...`);

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-app-key": key,
      },
      body: JSON.stringify({ prompt, provider }),
    });

    if (!response.ok) {
      let errorMsg = `Server returned status ${response.status}`;
      try {
        const errorJson = await response.json();
        errorMsg = errorJson.error || errorJson.details || errorMsg;
      } catch (e) {
        // Response wasn't JSON
      }
      throw new Error(errorMsg);
    }

    const result = await response.json();

    const folders = result.folders || [];
    const files = result.files || [];

    if (folders.length === 0 && files.length === 0) {
      console.warn("⚠️ Warning: No folders or files were generated by the AI model. Check your prompt or credentials.");
      process.exit(0);
    }

    console.log(`🛠️ Creating project directories...`);
    // Ensure all designated directories exist
    for (const folder of folders) {
      const folderPath = path.join(targetDir, folder);
      fs.ensureDirSync(folderPath);
      console.log(`  [Dir]  + ${folder}`);
    }

    console.log(`\n📝 Generating and formatting source code files...`);
    // Create and format all files
    for (const file of files) {
      if (!file.path || file.content === undefined) {
        continue;
      }

      const filePath = path.join(targetDir, file.path);
      
      // Ensure the parent directory for the file exists
      fs.ensureDirSync(path.dirname(filePath));

      let formattedContent = file.content;

      // Apply Prettier formatting based on file extension
      try {
        const ext = path.extname(file.path).toLowerCase();
        let parser = null;

        if (ext === ".ts" || ext === ".tsx") {
          parser = "typescript";
        } else if (ext === ".js" || ext === ".jsx") {
          parser = "babel";
        } else if (ext === ".json") {
          parser = "json";
        } else if (ext === ".css") {
          parser = "css";
        } else if (ext === ".html") {
          parser = "html";
        } else if (ext === ".md") {
          parser = "markdown";
        }

        if (parser) {
          formattedContent = await prettier.format(file.content, {
            parser,
            semi: true,
            singleQuote: true,
            trailingComma: "es5",
            printWidth: 100,
          });
        }
      } catch (prettierError) {
        // Fall back gracefully to writing original raw content if prettier fails
        console.warn(`  ⚠️ Prettier formatting skipped for ${file.path}: ${prettierError.message}`);
      }

      // Write content to disk
      fs.writeFileSync(filePath, formattedContent, "utf8");
      console.log(`  [File] + ${file.path}`);
    }

    console.log(`\n==================================================`);
    console.log(`🎉 Success! Codebase generated successfully.`);
    console.log(`📂 Inspect your new files in: ${targetDir}`);
    console.log(`==================================================\n`);

  } catch (error) {
    console.error(`\n❌ Error during generation:`);
    console.error(`   ${error.message}\n`);
    process.exit(1);
  }
}

main();
